export const ACTION_CHANGE_USER = "ACTION_CHANGE_USER";
export const ACTION_CHANGE_STR_TO_FIND = "ACTION_CHANGE_STR_TO_FIND";
export const ACTION_ADD_BLOCKS = "ACTION_ADD_BLOCKS";
export const USER_HAS_ERRORED = "USER_HAS_ERRORED";
